; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "LST"
#define MyAppVersion "1.0"
#define MyAppPublisher "JKFT"
#define MyAppExeName "GUI.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{7D4A872A-801C-479F-91F3-294702685CD1}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=admin
OutputBaseFilename=mysetup
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\javier.kipen\Documents\GitHub\LST\GUI\bin\Release\net10.0-windows\win-x64\publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\javier.kipen\Documents\GitHub\LST\THIRD-PARTY SOFTWARE NOTICES.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\javier.kipen\Documents\GitHub\LST\LICENSE.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\javier.kipen\Documents\GitHub\LST\LICENSES\*"; DestDir: "{app}\LICENSES"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Use the "issigverify" flag or the "Hash" parameter to verify downloads
Source: "https://huggingface.co/KBLab/kb-whisper-tiny/resolve/main/ggml-model.bin"; DestDir: "{app}\Models"; DestName: "kb-ggml-tiny.bin"; ExternalSize: "81788928"; Flags: ignoreversion external download
Source: "https://huggingface.co/KBLab/kb-whisper-base/resolve/main/ggml-model.bin"; DestDir: "{app}\Models"; DestName: "kb-ggml-base.bin"; ExternalSize: "155189248"; Flags: ignoreversion external download
Source: "https://huggingface.co/KBLab/kb-whisper-small/resolve/main/ggml-model.bin"; DestDir: "{app}\Models"; DestName: "kb-ggml-small.bin"; ExternalSize: "507510784"; Flags: ignoreversion external download
Source: "https://huggingface.co/KBLab/kb-whisper-medium/resolve/main/ggml-model.bin"; DestDir: "{app}\Models"; DestName: "kb-ggml-medium.bin"; ExternalSize: "1635778560"; Flags: ignoreversion external download
Source: "https://huggingface.co/KBLab/kb-whisper-large/resolve/main/ggml-model.bin"; DestDir: "{app}\Models"; DestName: "kb-ggml-large.bin"; ExternalSize: "3460300800"; Flags: ignoreversion external download
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

